service: github-repos

provider:
  name: aws
  runtime: nodejs6.10
  stage: production

functions:
  app:
    handler: index.handler
    environment:
      TOKEN: ${file(./secrets.yml):token}
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
custom:
  customDomain:
    domainName: oss-repos.filiosoft.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

plugins:
  - serverless-offline
  - serverless-domain-manager